# Generated by Django 3.1.3 on 2022-02-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20220213_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mastery_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=10)),
                ('join_date', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.TextField()),
                ('recent_login', models.DateTimeField()),
                ('marking', models.CharField(max_length=5)),
            ],
        ),
    ]
