# Generated by Django 3.1.3 on 2022-02-14 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_mastery_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastery_user',
            name='no',
        ),
    ]
