# Generated by Django 3.1.3 on 2022-02-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_auto_20220214_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastery_user',
            name='path',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
