# Generated by Django 3.1.3 on 2022-02-14 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0010_mastery_user_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mastery_user',
            old_name='path',
            new_name='knowing_path',
        ),
    ]
